In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [40]:
dataset = pd.read_csv('videos-stats.csv')
x = dataset.iloc[:5, :7].values
y = dataset.iloc[:5,  -1].values

In [41]:
print(x)

[[0
  'Apple Pay Is Killing the Physical Wallet After Only Eight Years | Tech News Briefing Podcast | WSJ'
  'wAZZ-UWGVHI' '2022-08-23' 'tech' 3407.0 672.0]
 [1 'The most EXPENSIVE thing I own.' 'b3x28s61q3c' '2022-08-24' 'tech'
  76779.0 4306.0]
 [2 'My New House Gaming Setup is SICK!' '4mgePWWCAmA' '2022-08-23'
  'tech' 63825.0 3338.0]
 [3
  'Petrol Vs Liquid Nitrogen | Freezing Experiment | പെട്രോളിനെ ഐസ് ആകാൻ പറ്റുമോ | M4 Tech |'
  'kXiYSI7H2b0' '2022-08-23' 'tech' 71566.0 1426.0]
 [4 'Best Back to School Tech 2022!' 'ErMwWXQxHp0' '2022-08-08' 'tech'
  96513.0 5155.0]]


In [42]:
print(y)

[ 135612. 1758063. 1564007.  922918. 1855644.]


In [43]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 5:7])
x[:, 5:7] = imputer.transform(x[:, 5:7])

In [44]:
print(x)

[[0
  'Apple Pay Is Killing the Physical Wallet After Only Eight Years | Tech News Briefing Podcast | WSJ'
  'wAZZ-UWGVHI' '2022-08-23' 'tech' 3407.0 672.0]
 [1 'The most EXPENSIVE thing I own.' 'b3x28s61q3c' '2022-08-24' 'tech'
  76779.0 4306.0]
 [2 'My New House Gaming Setup is SICK!' '4mgePWWCAmA' '2022-08-23'
  'tech' 63825.0 3338.0]
 [3
  'Petrol Vs Liquid Nitrogen | Freezing Experiment | പെട്രോളിനെ ഐസ് ആകാൻ പറ്റുമോ | M4 Tech |'
  'kXiYSI7H2b0' '2022-08-23' 'tech' 71566.0 1426.0]
 [4 'Best Back to School Tech 2022!' 'ErMwWXQxHp0' '2022-08-08' 'tech'
  96513.0 5155.0]]


In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [46]:
print(x)

[[1.0 0.0 0.0 0.0 0.0
  'Apple Pay Is Killing the Physical Wallet After Only Eight Years | Tech News Briefing Podcast | WSJ'
  'wAZZ-UWGVHI' '2022-08-23' 'tech' 3407.0 672.0]
 [0.0 1.0 0.0 0.0 0.0 'The most EXPENSIVE thing I own.' 'b3x28s61q3c'
  '2022-08-24' 'tech' 76779.0 4306.0]
 [0.0 0.0 1.0 0.0 0.0 'My New House Gaming Setup is SICK!' '4mgePWWCAmA'
  '2022-08-23' 'tech' 63825.0 3338.0]
 [0.0 0.0 0.0 1.0 0.0
  'Petrol Vs Liquid Nitrogen | Freezing Experiment | പെട്രോളിനെ ഐസ് ആകാൻ പറ്റുമോ | M4 Tech |'
  'kXiYSI7H2b0' '2022-08-23' 'tech' 71566.0 1426.0]
 [0.0 0.0 0.0 0.0 1.0 'Best Back to School Tech 2022!' 'ErMwWXQxHp0'
  '2022-08-08' 'tech' 96513.0 5155.0]]


In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [48]:
print(y)

[0 3 2 1 4]


In [49]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [50]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 'The most EXPENSIVE thing I own.' 'b3x28s61q3c'
  '2022-08-24' 'tech' 76779.0 4306.0]
 [0.0 0.0 0.0 0.0 1.0 'Best Back to School Tech 2022!' 'ErMwWXQxHp0'
  '2022-08-08' 'tech' 96513.0 5155.0]
 [1.0 0.0 0.0 0.0 0.0
  'Apple Pay Is Killing the Physical Wallet After Only Eight Years | Tech News Briefing Podcast | WSJ'
  'wAZZ-UWGVHI' '2022-08-23' 'tech' 3407.0 672.0]
 [0.0 0.0 0.0 1.0 0.0
  'Petrol Vs Liquid Nitrogen | Freezing Experiment | പെട്രോളിനെ ഐസ് ആകാൻ പറ്റുമോ | M4 Tech |'
  'kXiYSI7H2b0' '2022-08-23' 'tech' 71566.0 1426.0]]


In [51]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 'My New House Gaming Setup is SICK!' '4mgePWWCAmA'
  '2022-08-23' 'tech' 63825.0 3338.0]]


In [52]:
print(y_train)

[3 4 0 1]


In [53]:
print(y_test)

[2]


In [54]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 2:4] = sc.fit_transform(x_train[:, 2:4])
x_test[:, 2:4] = sc.transform(x_test[:, 2:4])

In [55]:
print(x_train)

[[0.0 1.0 0.0 -0.5773502691896258 0.0 'The most EXPENSIVE thing I own.'
  'b3x28s61q3c' '2022-08-24' 'tech' 76779.0 4306.0]
 [0.0 0.0 0.0 -0.5773502691896258 1.0 'Best Back to School Tech 2022!'
  'ErMwWXQxHp0' '2022-08-08' 'tech' 96513.0 5155.0]
 [1.0 0.0 0.0 -0.5773502691896258 0.0
  'Apple Pay Is Killing the Physical Wallet After Only Eight Years | Tech News Briefing Podcast | WSJ'
  'wAZZ-UWGVHI' '2022-08-23' 'tech' 3407.0 672.0]
 [0.0 0.0 0.0 1.7320508075688774 0.0
  'Petrol Vs Liquid Nitrogen | Freezing Experiment | പെട്രോളിനെ ഐസ് ആകാൻ പറ്റുമോ | M4 Tech |'
  'kXiYSI7H2b0' '2022-08-23' 'tech' 71566.0 1426.0]]


In [56]:
print(x_test)

[[0.0 0.0 1.0 -0.5773502691896258 0.0
  'My New House Gaming Setup is SICK!' '4mgePWWCAmA' '2022-08-23' 'tech'
  63825.0 3338.0]]
